apiVersion: v1
kind: Service
metadata:
  name: kube-reverse-proxy
  namespace: system
  labels:
    k8s-app: kube-reverse-proxy
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeReverseProxy"
spec:
  selector:
    k8s-app: kube-reverse-proxy
    version: v0.1.0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
    nodePort: 30080
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
    nodePort: 30443
  type: NodePort
